[package]
name = "doppely"
version = "0.0.1"
edition = "2024"

[features]
default = ["lightyear/raw_connection", "udp"]
netcode = ["lightyear/netcode"]
udp = ["lightyear/udp"]

client = [
    "bevy/3d",
    "bevy/3d_bevy_render",
    "bevy/3d_api",
    "bevy/bevy_ui",
    "bevy/bevy_text",
    "bevy/bevy_ui_render",
    "bevy/bevy_render",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_winit",
    "bevy/bevy_window",
    "bevy/default_font",
    "lightyear/client"
]

server = [
    "dep:dfdx",
    "lightyear/server",
    "dep:strum"
]

[dependencies]
serde = "1.0.229"
clap = { version = "4.6.7", features = ["derive"] }

# Управление вводом для клиент-серверного взаимодействия
leafwing-input-manager = "0.21.0"

# Сетевая библиотека
lightyear = { version="0.30", features = ["avian3d", "interpolation", "prediction", "replication", "leafwing"] }

# Библиотека для нейронной сети
dfdx = { version = "0.13.0", features = ["cuda"], optional = true }
strum = { version = "0.28.0", features = ["derive"], optional = true }

# Движок для обработки логики игры и рендеринга
[dependencies.bevy]
version = "0.19.1"
default-features = false
features = [
    "std",
    "bevy_state",
    "bevy_asset",
    "bevy_log"
]

# Движок физики в 3d
[dependencies.avian3d]
version = "0.7"
features = ["serialize"]

[[bin]]
name = "client"
path = "src/client/mod.rs"
required-features = ["client"]

[[bin]]
name = "server"
path = "src/server/mod.rs"
required-features = ["server"]

[profile.release]
lto = "thin"
strip = true
